"""Multi-round active learning loop for the 6D basin dataset.

Iterates: train → find uncertain regions → sample near them → integrate →
merge → retrain → evaluate on a fixed test set → check convergence.

Uncertainty is measured by both model prediction entropy and k-NN label
disagreement.  New samples are generated by perturbing uncertain points
in the full 7D space (S² tangent-plane for shape + Gaussian for momenta).

Outputs per round:
    data/al_round_{i}.parquet          new samples from round i
    data/al_cumulative_{i}.parquet     full dataset through round i
    data/al_model_{i}.eqx              model checkpoint
    data/al_metrics.npz                metrics history across rounds
    figures/al_convergence.png         F1/accuracy vs round
"""
from __future__ import annotations

import argparse
import sys
import time
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

import jax

jax.config.update("jax_enable_x64", True)

import jax.numpy as jnp
import numpy as np
import pandas as pd
import pyarrow as pa
import pyarrow.parquet as pq
from scipy.spatial import cKDTree

jax.config.update("jax_enable_x64", False)

import equinox as eqx
import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import optax

from mega3bp.batch import integrate_batch
from mega3bp.dynamics import angular_momentum, total_energy
from mega3bp.escape import LABEL_NAMES
from mega3bp.ml import N_CLASSES, BasinMLP, loss_fn, predict, predict_proba, stratified_split
from mega3bp.shape_sphere import jacobi_momenta_to_body, shape_to_config
from mega3bp.style import PALETTE, apply_dirac_style

CLASS_NAMES = ["bound", "body1_escape", "body2_escape", "body3_escape"]
FEATURE_COLS = ["shape_n1", "shape_n2", "shape_n3", "pi1x", "pi1y", "pi2x", "pi2y"]

H = 0.01
T_MAX = 500.0
N_STEPS = int(round(T_MAX / H))
R_ESCAPE = 5.0
BINARY_FACTOR = 2.0
R_CLOSE = 1e-3
CHUNK = 65536


# ---- Perturbation -----------------------------------------------------------

def perturb_6d(features: np.ndarray, sigma_shape: float, sigma_mom: float,
               n_target: int, rng: np.random.Generator) -> np.ndarray:
    """Perturb uncertain 7D points: tangent-plane on S² + Gaussian on momenta."""
    N = features.shape[0]
    if N == 0:
        return np.empty((0, 7), dtype=np.float64)
    n_per = max(1, (n_target + N - 1) // N)
    parts = []
    for _ in range(n_per):
        n = features[:, :3]
        noise_s = rng.normal(0, sigma_shape, (N, 3))
        dot = np.sum(noise_s * n, axis=-1, keepdims=True)
        tangent = noise_s - dot * n
        moved = n + tangent
        moved /= np.linalg.norm(moved, axis=-1, keepdims=True)

        noise_m = rng.normal(0, sigma_mom, (N, 4))
        moved_m = features[:, 3:] + noise_m
        parts.append(np.concatenate([moved, moved_m], axis=-1))
    out = np.concatenate(parts, axis=0)
    rng.shuffle(out)
    return out[:n_target]


# ---- Uncertainty detection --------------------------------------------------

def knn_boundary_mask(features: np.ndarray, labels: np.ndarray,
                      k: int = 12) -> np.ndarray:
    """True where any of k nearest neighbors has a different label."""
    tree = cKDTree(features)
    _, idx = tree.query(features, k=k + 1)
    neighbor_labels = labels[idx[:, 1:]]
    disagreement = np.any(neighbor_labels != labels[:, None], axis=1)
    return disagreement


def entropy_mask(model, features_jax: jnp.ndarray, threshold: float,
                 batch: int = 16384) -> np.ndarray:
    """True where prediction entropy exceeds threshold."""
    all_ent = []
    for start in range(0, features_jax.shape[0], batch):
        probs = predict_proba(model, features_jax[start:start + batch])
        ent = -jnp.sum(probs * jnp.log(probs + 1e-10), axis=-1)
        all_ent.append(np.asarray(ent))
    ent_all = np.concatenate(all_ent)
    return ent_all > threshold


# ---- Integration ------------------------------------------------------------

def integrate_new_ics(features_7d: np.ndarray) -> dict[str, np.ndarray]:
    """Integrate 7D ICs and return outcome arrays."""
    jax.config.update("jax_enable_x64", True)
    N = features_7d.shape[0]

    shape_np = features_7d[:, :3]
    pi_np = features_7d[:, 3:]
    shape_jax = jnp.asarray(shape_np, dtype=jnp.float64)
    pi_jax = jnp.asarray(pi_np, dtype=jnp.float64)
    q = jax.vmap(lambda n: shape_to_config(n, inertia=1.0))(shape_jax)
    p = jax.vmap(lambda pi: jacobi_momenta_to_body(pi[:2], pi[2:]))(pi_jax)
    E = np.asarray(total_energy(q, p))
    L = np.asarray(angular_momentum(q, p))

    all_labels = np.empty(N, dtype=np.int8)
    all_etimes = np.empty(N, dtype=np.float64)
    all_amb = np.empty(N, dtype=np.bool_)
    all_rmin = np.empty(N, dtype=np.float64)
    all_maxsep = np.empty(N, dtype=np.float64)

    n_chunks = (N + CHUNK - 1) // CHUNK
    for i in range(n_chunks):
        lo = i * CHUNK
        hi = min(lo + CHUNK, N)
        actual = hi - lo
        q_c, p_c = q[lo:hi], p[lo:hi]
        if actual < CHUNK:
            pad = CHUNK - actual
            q_c = jnp.concatenate([q_c, jnp.repeat(q_c[:1], pad, axis=0)])
            p_c = jnp.concatenate([p_c, jnp.repeat(p_c[:1], pad, axis=0)])
        out = integrate_batch(q_c, p_c, H, N_STEPS,
                              r_escape=R_ESCAPE, binary_factor=BINARY_FACTOR, r_close=R_CLOSE)
        jax.block_until_ready(out["label"])
        for k, arr in [("label", all_labels), ("escape_time", all_etimes),
                        ("ambiguous", all_amb), ("r_min_ever", all_rmin), ("max_sep", all_maxsep)]:
            arr[lo:hi] = np.asarray(out[k])[:actual]
    jax.config.update("jax_enable_x64", False)

    return {
        "shape_n1": shape_np[:, 0], "shape_n2": shape_np[:, 1], "shape_n3": shape_np[:, 2],
        "pi1x": pi_np[:, 0], "pi1y": pi_np[:, 1], "pi2x": pi_np[:, 2], "pi2y": pi_np[:, 3],
        "energy": E, "angular_momentum": L,
        "label": all_labels, "escape_time": all_etimes,
        "ambiguous": all_amb, "r_min_ever": all_rmin, "max_sep": all_maxsep,
    }


# ---- Training ---------------------------------------------------------------

def train_model(inputs, labels, log_t, finite, args, key):
    """Train BasinMLP, return (model, metrics_on_val)."""
    key, split_key, model_key = jax.random.split(key, 3)
    x = jnp.asarray(inputs, dtype=jnp.float32)
    y = jnp.asarray(labels, dtype=jnp.int32)
    lt = jnp.asarray(log_t, dtype=jnp.float32)
    m = jnp.asarray(finite)

    train_idx, val_idx, _ = stratified_split(y, split_key)

    class_counts = np.array([int((labels[np.asarray(train_idx)] == i).sum()) for i in range(N_CLASSES)])
    class_w = 1.0 / np.maximum(class_counts, 1)
    class_w = class_w / class_w.mean()
    class_w_jax = jnp.asarray(class_w, dtype=jnp.float32)

    model = BasinMLP(in_dim=args.in_dim, hidden=args.hidden, n_layers=args.layers,
                     out_dim=N_CLASSES + 1, key=model_key)

    schedule = optax.warmup_cosine_decay_schedule(
        init_value=args.lr / 10, peak_value=args.lr, warmup_steps=300,
        decay_steps=args.al_epochs * (train_idx.shape[0] // args.batch),
        end_value=args.lr / 50)
    opt = optax.adamw(learning_rate=schedule, weight_decay=1e-4)
    opt_state = opt.init(eqx.filter(model, eqx.is_array))

    @eqx.filter_jit
    def step(model, opt_state, xb, yb, ltb, mb):
        def f(m): return loss_fn(m, xb, yb, ltb, mb, class_w_jax)
        (_, metrics), grads = eqx.filter_value_and_grad(f, has_aux=True)(model)
        updates, opt_state = opt.update(grads, opt_state, eqx.filter(model, eqx.is_array))
        return eqx.apply_updates(model, updates), opt_state, metrics

    x_tr, y_tr = x[train_idx], y[train_idx]
    lt_tr, m_tr = lt[train_idx], m[train_idx]
    x_val, y_val = x[val_idx], y[val_idx]
    lt_val, m_val = lt[val_idx], m[val_idx]

    best_acc, best_model = -1.0, model
    for ep in range(args.al_epochs):
        key, ek = jax.random.split(key)
        idx = jax.random.permutation(ek, x_tr.shape[0])
        for s in range(0, x_tr.shape[0], args.batch):
            sel = idx[s:s + args.batch]
            model, opt_state, _ = step(model, opt_state, x_tr[sel], y_tr[sel],
                                       lt_tr[sel], m_tr[sel])
        vm = loss_fn(model, x_val, y_val, lt_val, m_val, class_w_jax)
        va = float(vm[1]["accuracy"])
        if va > best_acc:
            best_acc = va
            best_model = jax.tree.map(lambda x: x, model)
    return best_model


# ---- Evaluation on fixed test set -------------------------------------------

def evaluate_model(model, x_test, y_test, lt_test, m_test):
    y_pred_parts, lt_pred_parts = [], []
    for s in range(0, x_test.shape[0], 16384):
        p, lt = predict(model, x_test[s:s + 16384])
        y_pred_parts.append(np.asarray(p))
        lt_pred_parts.append(np.asarray(lt))
    y_pred = np.concatenate(y_pred_parts)
    lt_pred = np.concatenate(lt_pred_parts)
    y_true = np.asarray(y_test)
    acc = float((y_pred == y_true).mean())
    confusion = np.zeros((N_CLASSES, N_CLASSES), dtype=np.int64)
    for t, p in zip(y_true, y_pred):
        confusion[int(t), int(p)] += 1
    f1s = []
    for i in range(N_CLASSES):
        tp = confusion[i, i]
        fn = confusion[i, :].sum() - tp
        fp = confusion[:, i].sum() - tp
        prec = tp / max(tp + fp, 1)
        rec = tp / max(tp + fn, 1)
        f1s.append(2 * prec * rec / max(prec + rec, 1e-12))
    macro_f1 = float(np.mean(f1s))
    return {"acc": acc, "macro_f1": macro_f1, "per_class_f1": f1s, "confusion": confusion}


# ---- Main loop --------------------------------------------------------------

def main() -> int:
    apply_dirac_style()
    parser = argparse.ArgumentParser()
    parser.add_argument("--parquet", type=str, required=True)
    parser.add_argument("--rounds", type=int, default=5)
    parser.add_argument("--samples_per_round", type=int, default=200_000)
    parser.add_argument("--sigma_shape", type=float, default=0.005)
    parser.add_argument("--sigma_mom", type=float, default=0.1)
    parser.add_argument("--k_neighbors", type=int, default=20)
    parser.add_argument("--entropy_threshold", type=float, default=0.8)
    parser.add_argument("--al_epochs", type=int, default=30)
    parser.add_argument("--batch", type=int, default=4096)
    parser.add_argument("--lr", type=float, default=3e-4)
    parser.add_argument("--hidden", type=int, default=384)
    parser.add_argument("--layers", type=int, default=6)
    parser.add_argument("--in_dim", type=int, default=7)
    parser.add_argument("--seed", type=int, default=0xA10001)
    parser.add_argument("--convergence_delta", type=float, default=0.005,
                        help="stop if F1 improves less than this for 2 rounds")
    args = parser.parse_args()

    out_data = PROJECT_ROOT / "data"
    out_fig = PROJECT_ROOT / "figures"
    out_data.mkdir(exist_ok=True)
    out_fig.mkdir(exist_ok=True)

    print(f"=== active learning loop ===")
    print(f"rounds       : {args.rounds}")
    print(f"samples/round: {args.samples_per_round:,}")
    print(f"σ_shape      : {args.sigma_shape}")
    print(f"σ_mom        : {args.sigma_mom}")
    print()

    df = pd.read_parquet(args.parquet)
    df = df[df.label != -1].reset_index(drop=True)
    print(f"initial dataset: {len(df):,} non-ambiguous rows")

    key = jax.random.PRNGKey(args.seed)
    rng = np.random.default_rng(args.seed)

    # Fixed test set from initial data (never changes)
    all_labels = df.label.to_numpy().astype(np.int32)
    key, split_key = jax.random.split(key)
    _, _, test_idx_jax = stratified_split(jnp.asarray(all_labels), split_key)
    test_idx = np.asarray(test_idx_jax)
    test_features = df.iloc[test_idx][FEATURE_COLS].to_numpy(dtype=np.float32)
    test_labels = all_labels[test_idx]
    test_etimes = df.iloc[test_idx].escape_time.to_numpy(dtype=np.float32)
    test_finite = np.isfinite(test_etimes)
    test_log_t = np.zeros_like(test_etimes)
    test_log_t[test_finite] = np.log(test_etimes[test_finite])
    x_test = jnp.asarray(test_features)
    y_test = jnp.asarray(test_labels, dtype=jnp.int32)
    lt_test = jnp.asarray(test_log_t, dtype=jnp.float32)
    m_test = jnp.asarray(test_finite)
    print(f"fixed test set: {len(test_idx):,}")

    # Remove test indices from training pool
    train_mask = np.ones(len(df), dtype=bool)
    train_mask[test_idx] = False
    df_train = df.loc[train_mask].reset_index(drop=True)

    history = {"round": [], "n_total": [], "acc": [], "macro_f1": [],
               "per_class_f1": [], "n_uncertain": [], "wall_time": []}
    stall_count = 0
    prev_f1 = 0.0

    for rnd in range(args.rounds + 1):
        t0 = time.perf_counter()
        print(f"\n{'='*60}")
        print(f"Round {rnd}: {len(df_train):,} training samples")

        features_np = df_train[FEATURE_COLS].to_numpy(dtype=np.float32)
        labels_np = df_train.label.to_numpy().astype(np.int32)
        etimes_np = df_train.escape_time.to_numpy(dtype=np.float32)
        finite_np = np.isfinite(etimes_np)
        log_t_np = np.zeros_like(etimes_np, dtype=np.float32)
        log_t_np[finite_np] = np.log(etimes_np[finite_np])

        # Train
        key, train_key = jax.random.split(key)
        print("  training...")
        model = train_model(features_np, labels_np, log_t_np, finite_np, args, train_key)

        # Evaluate on fixed test set
        metrics = evaluate_model(model, x_test, y_test, lt_test, m_test)
        wall = time.perf_counter() - t0
        print(f"  acc={metrics['acc']:.4f}  F1={metrics['macro_f1']:.4f}  "
              f"per-class={[f'{f:.3f}' for f in metrics['per_class_f1']]}  [{wall:.1f}s]")

        history["round"].append(rnd)
        history["n_total"].append(len(df_train))
        history["acc"].append(metrics["acc"])
        history["macro_f1"].append(metrics["macro_f1"])
        history["per_class_f1"].append(metrics["per_class_f1"])
        history["n_uncertain"].append(0)
        history["wall_time"].append(wall)

        # Save model checkpoint
        eqx.tree_serialise_leaves(str(out_data / f"al_model_{rnd}.eqx"), model)

        if rnd == args.rounds:
            break

        # Check convergence
        delta = metrics["macro_f1"] - prev_f1
        if rnd > 0 and delta < args.convergence_delta:
            stall_count += 1
            print(f"  ΔF1={delta:.4f} < {args.convergence_delta} (stall {stall_count}/2)")
            if stall_count >= 2:
                print("  converged — stopping early")
                break
        else:
            stall_count = 0
        prev_f1 = metrics["macro_f1"]

        # Identify uncertain regions
        print("  detecting boundaries...")
        features_jax = jnp.asarray(features_np)
        ent_mask = entropy_mask(model, features_jax, args.entropy_threshold)
        knn_mask = knn_boundary_mask(features_np, labels_np, k=args.k_neighbors)
        uncertain = ent_mask | knn_mask
        n_uncertain = int(uncertain.sum())
        history["n_uncertain"][-1] = n_uncertain
        print(f"  uncertain: {n_uncertain:,} ({100*n_uncertain/len(df_train):.1f}%)")
        print(f"    entropy>{args.entropy_threshold}: {int(ent_mask.sum()):,}  "
              f"kNN boundary: {int(knn_mask.sum()):,}")

        if n_uncertain == 0:
            print("  no uncertain points — stopping")
            break

        # Generate perturbations
        print(f"  generating {args.samples_per_round:,} perturbations...")
        candidates = features_np[uncertain]
        new_features = perturb_6d(candidates, args.sigma_shape, args.sigma_mom,
                                  args.samples_per_round, rng)

        # Integrate
        print(f"  integrating {new_features.shape[0]:,} new ICs...")
        new_data = integrate_new_ics(new_features)

        # Save round parquet
        new_df = pd.DataFrame(new_data)
        round_path = out_data / f"al_round_{rnd+1}.parquet"
        pq.write_table(pa.Table.from_pandas(new_df), round_path, compression="snappy")
        print(f"  saved {round_path} ({round_path.stat().st_size / 1e6:.1f} MB)")

        # Merge (drop ambiguous from new samples)
        new_df = new_df[new_df.label != -1].reset_index(drop=True)
        df_train = pd.concat([df_train, new_df], ignore_index=True)

    # ---- Save final metrics ----
    np.savez(out_data / "al_metrics.npz",
             rounds=np.array(history["round"]),
             n_total=np.array(history["n_total"]),
             acc=np.array(history["acc"]),
             macro_f1=np.array(history["macro_f1"]),
             per_class_f1=np.array(history["per_class_f1"]),
             n_uncertain=np.array(history["n_uncertain"]),
             wall_time=np.array(history["wall_time"]))

    # ---- Convergence plot ----
    rounds = np.array(history["round"])
    fig, axes = plt.subplots(1, 3, figsize=(16, 5), dpi=150)
    fig.patch.set_facecolor(PALETTE["bg_deep"])

    axes[0].plot(rounds, history["acc"], "o-", color=PALETTE["cyan"], lw=2, ms=6)
    axes[0].set_xlabel("round"); axes[0].set_ylabel("accuracy")
    axes[0].set_title("test accuracy vs round")

    axes[1].plot(rounds, history["macro_f1"], "s-", color=PALETTE["lime"], lw=2, ms=6)
    axes[1].set_xlabel("round"); axes[1].set_ylabel("macro F1")
    axes[1].set_title("test macro F1 vs round")

    n_tot = np.array(history["n_total"])
    axes[2].plot(n_tot / 1e6, history["macro_f1"], "D-", color=PALETTE["lavender"], lw=2, ms=6)
    axes[2].set_xlabel("training samples (M)"); axes[2].set_ylabel("macro F1")
    axes[2].set_title("F1 vs dataset size")

    fig.suptitle("Active learning convergence (6D)", color=PALETTE["text"], fontsize=14, y=1.02)
    fig.tight_layout()
    fig.savefig(out_fig / "al_convergence.png", facecolor=PALETTE["bg_deep"])
    plt.close(fig)

    print(f"\n=== active learning complete ===")
    print(f"  rounds      : {len(history['round'])}")
    print(f"  final acc   : {history['acc'][-1]:.4f}")
    print(f"  final F1    : {history['macro_f1'][-1]:.4f}")
    print(f"  final N     : {history['n_total'][-1]:,}")
    print(f"  saved al_convergence.png, al_metrics.npz")
    return 0


if __name__ == "__main__":
    sys.exit(main())
